version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3DEngine\$env:CONFIGURATION\3DEngine.exe C:\projects\3DEngine\Game\.
artifacts:
- path: 3DEngine\Game
  name: 3DEngine
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: Rz1LCoPhCzLLNr4ndqTt3LmP5uMiqE3G4v+9AJmJiwiGlOmCvN0jhavjKFCDJ737
  artifact: 3DEngine
  draft: true