version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\3D--Engine\3DEngine\$env:CONFIGURATION\3DEngine.exe C:\projects\3D--Engine\3DEngine\Game\.
artifacts:
- path: 3D Engine\Game
  name: game_files
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: Rz1LCoPhCzLLNr4ndqTt3LmP5uMiqE3G4v+9AJmJiwiGlOmCvN0jhavjKFCDJ737
  artifact: game-files
  draft: true